CREATE TABLE IF NOT EXISTS Ambulances_Audit (
    Id NVARCHAR(MAX) PRIMARY KEY,
    TableName VARCHAR(100),
    RecordID NVARCHAR(MAX),
    CreatedBy VARCHAR(50),
    CreatedDateTime DATETIME,
    LastModifiedBy VARCHAR(50),
    LastModifiedDateTime DATETIME,
    IsActive BIT,
    IsSoftDeleted BIT,
    IsHardDeleted BIT,
    RowVersion INT,
    DeletedBy VARCHAR(50),
    DeletedDateTime DATETIME,
    SourceSystem VARCHAR(100),
    CreatedByIp VARCHAR(50),
    LastModifiedByIp VARCHAR(50),
    AuditId NVARCHAR(MAX),
    TenantId NVARCHAR(MAX),
    CorrelationId NVARCHAR(MAX)
);

CREATE TABLE IF NOT EXISTS Appointments_Audit (
    Id NVARCHAR(MAX) PRIMARY KEY,
    TableName VARCHAR(100),
    RecordID NVARCHAR(MAX),
    CreatedBy VARCHAR(50),
    CreatedDateTime DATETIME,
    LastModifiedBy VARCHAR(50),
    LastModifiedDateTime DATETIME,
    IsActive BIT,
    IsSoftDeleted BIT,
    IsHardDeleted BIT,
    RowVersion INT,
    DeletedBy VARCHAR(50),
    DeletedDateTime DATETIME,
    SourceSystem VARCHAR(100),
    CreatedByIp VARCHAR(50),
    LastModifiedByIp VARCHAR(50),
    AuditId NVARCHAR(MAX),
    TenantId NVARCHAR(MAX),
    CorrelationId NVARCHAR(MAX)
);

CREATE TABLE IF NOT EXISTS Beds_Audit (
    Id NVARCHAR(MAX) PRIMARY KEY,
    TableName VARCHAR(100),
    RecordID NVARCHAR(MAX),
    CreatedBy VARCHAR(50),
    CreatedDateTime DATETIME,
    LastModifiedBy VARCHAR(50),
    LastModifiedDateTime DATETIME,
    IsActive BIT,
    IsSoftDeleted BIT,
    IsHardDeleted BIT,
    RowVersion INT,
    DeletedBy VARCHAR(50),
    DeletedDateTime DATETIME,
    SourceSystem VARCHAR(100),
    CreatedByIp VARCHAR(50),
    LastModifiedByIp VARCHAR(50),
    AuditId NVARCHAR(MAX),
    TenantId NVARCHAR(MAX),
    CorrelationId NVARCHAR(MAX)
);

CREATE TABLE IF NOT EXISTS CareGivers_Audit (
    Id NVARCHAR(MAX) PRIMARY KEY,
    TableName VARCHAR(100),
    RecordID NVARCHAR(MAX),
    CreatedBy VARCHAR(50),
    CreatedDateTime DATETIME,
    LastModifiedBy VARCHAR(50),
    LastModifiedDateTime DATETIME,
    IsActive BIT,
    IsSoftDeleted BIT,
    IsHardDeleted BIT,
    RowVersion INT,
    DeletedBy VARCHAR(50),
    DeletedDateTime DATETIME,
    SourceSystem VARCHAR(100),
    CreatedByIp VARCHAR(50),
    LastModifiedByIp VARCHAR(50),
    AuditId NVARCHAR(MAX),
    TenantId NVARCHAR(MAX),
    CorrelationId NVARCHAR(MAX)
);

CREATE TABLE IF NOT EXISTS Departments_Audit (
    Id NVARCHAR(MAX) PRIMARY KEY,
    TableName VARCHAR(100),
    RecordID NVARCHAR(MAX),
    CreatedBy VARCHAR(50),
    CreatedDateTime DATETIME,
    LastModifiedBy VARCHAR(50),
    LastModifiedDateTime DATETIME,
    IsActive BIT,
    IsSoftDeleted BIT,
    IsHardDeleted BIT,
    RowVersion INT,
    DeletedBy VARCHAR(50),
    DeletedDateTime DATETIME,
    SourceSystem VARCHAR(100),
    CreatedByIp VARCHAR(50),
    LastModifiedByIp VARCHAR(50),
    AuditId NVARCHAR(MAX),
    TenantId NVARCHAR(MAX),
    CorrelationId NVARCHAR(MAX)
);

CREATE TABLE IF NOT EXISTS DischargeSummaries_Audit (
    Id NVARCHAR(MAX) PRIMARY KEY,
    TableName VARCHAR(100),
    RecordID NVARCHAR(MAX),
    CreatedBy VARCHAR(50),
    CreatedDateTime DATETIME,
    LastModifiedBy VARCHAR(50),
    LastModifiedDateTime DATETIME,
    IsActive BIT,
    IsSoftDeleted BIT,
    IsHardDeleted BIT,
    RowVersion INT,
    DeletedBy VARCHAR(50),
    DeletedDateTime DATETIME,
    SourceSystem VARCHAR(100),
    CreatedByIp VARCHAR(50),
    LastModifiedByIp VARCHAR(50),
    AuditId NVARCHAR(MAX),
    TenantId NVARCHAR(MAX),
    CorrelationId NVARCHAR(MAX)
);

CREATE TABLE IF NOT EXISTS Doctors_Audit (
    Id NVARCHAR(MAX) PRIMARY KEY,
    TableName VARCHAR(100),
    RecordID NVARCHAR(MAX),
    CreatedBy VARCHAR(50),
    CreatedDateTime DATETIME,
    LastModifiedBy VARCHAR(50),
    LastModifiedDateTime DATETIME,
    IsActive BIT,
    IsSoftDeleted BIT,
    IsHardDeleted BIT,
    RowVersion INT,
    DeletedBy VARCHAR(50),
    DeletedDateTime DATETIME,
    SourceSystem VARCHAR(100),
    CreatedByIp VARCHAR(50),
    LastModifiedByIp VARCHAR(50),
    AuditId NVARCHAR(MAX),
    TenantId NVARCHAR(MAX),
    CorrelationId NVARCHAR(MAX)
);

CREATE TABLE IF NOT EXISTS Equipment_Audit (
    Id NVARCHAR(MAX) PRIMARY KEY,
    TableName VARCHAR(100),
    RecordID NVARCHAR(MAX),
    CreatedBy VARCHAR(50),
    CreatedDateTime DATETIME,
    LastModifiedBy VARCHAR(50),
    LastModifiedDateTime DATETIME,
    IsActive BIT,
    IsSoftDeleted BIT,
    IsHardDeleted BIT,
    RowVersion INT,
    DeletedBy VARCHAR(50),
    DeletedDateTime DATETIME,
    SourceSystem VARCHAR(100),
    CreatedByIp VARCHAR(50),
    LastModifiedByIp VARCHAR(50),
    AuditId NVARCHAR(MAX),
    TenantId NVARCHAR(MAX),
    CorrelationId NVARCHAR(MAX)
);

CREATE TABLE IF NOT EXISTS InsuranceProviders_Audit (
    Id NVARCHAR(MAX) PRIMARY KEY,
    TableName VARCHAR(100),
    RecordID NVARCHAR(MAX),
    CreatedBy VARCHAR(50),
    CreatedDateTime DATETIME,
    LastModifiedBy VARCHAR(50),
    LastModifiedDateTime DATETIME,
    IsActive BIT,
    IsSoftDeleted BIT,
    IsHardDeleted BIT,
    RowVersion INT,
    DeletedBy VARCHAR(50),
    DeletedDateTime DATETIME,
    SourceSystem VARCHAR(100),
    CreatedByIp VARCHAR(50),
    LastModifiedByIp VARCHAR(50),
    AuditId NVARCHAR(MAX),
    TenantId NVARCHAR(MAX),
    CorrelationId NVARCHAR(MAX)
);

CREATE TABLE IF NOT EXISTS Invoices_Audit (
    Id NVARCHAR(MAX) PRIMARY KEY,
    TableName VARCHAR(100),
    RecordID NVARCHAR(MAX),
    CreatedBy VARCHAR(50),
    CreatedDateTime DATETIME,
    LastModifiedBy VARCHAR(50),
    LastModifiedDateTime DATETIME,
    IsActive BIT,
    IsSoftDeleted BIT,
    IsHardDeleted BIT,
    RowVersion INT,
    DeletedBy VARCHAR(50),
    DeletedDateTime DATETIME,
    SourceSystem VARCHAR(100),
    CreatedByIp VARCHAR(50),
    LastModifiedByIp VARCHAR(50),
    AuditId NVARCHAR(MAX),
    TenantId NVARCHAR(MAX),
    CorrelationId NVARCHAR(MAX)
);

CREATE TABLE IF NOT EXISTS LabTests_Audit (
    Id NVARCHAR(MAX) PRIMARY KEY,
    TableName VARCHAR(100),
    RecordID NVARCHAR(MAX),
    CreatedBy VARCHAR(50),
    CreatedDateTime DATETIME,
    LastModifiedBy VARCHAR(50),
    LastModifiedDateTime DATETIME,
    IsActive BIT,
    IsSoftDeleted BIT,
    IsHardDeleted BIT,
    RowVersion INT,
    DeletedBy VARCHAR(50),
    DeletedDateTime DATETIME,
    SourceSystem VARCHAR(100),
    CreatedByIp VARCHAR(50),
    LastModifiedByIp VARCHAR(50),
    AuditId NVARCHAR(MAX),
    TenantId NVARCHAR(MAX),
    CorrelationId NVARCHAR(MAX)
);

CREATE TABLE IF NOT EXISTS MedicalRecords_Audit (
    Id NVARCHAR(MAX) PRIMARY KEY,
    TableName VARCHAR(100),
    RecordID NVARCHAR(MAX),
    CreatedBy VARCHAR(50),
    CreatedDateTime DATETIME,
    LastModifiedBy VARCHAR(50),
    LastModifiedDateTime DATETIME,
    IsActive BIT,
    IsSoftDeleted BIT,
    IsHardDeleted BIT,
    RowVersion INT,
    DeletedBy VARCHAR(50),
    DeletedDateTime DATETIME,
    SourceSystem VARCHAR(100),
    CreatedByIp VARCHAR(50),
    LastModifiedByIp VARCHAR(50),
    AuditId NVARCHAR(MAX),
    TenantId NVARCHAR(MAX),
    CorrelationId NVARCHAR(MAX)
);

CREATE TABLE IF NOT EXISTS Medications_Audit (
    Id NVARCHAR(MAX) PRIMARY KEY,
    TableName VARCHAR(100),
    RecordID NVARCHAR(MAX),
    CreatedBy VARCHAR(50),
    CreatedDateTime DATETIME,
    LastModifiedBy VARCHAR(50),
    LastModifiedDateTime DATETIME,
    IsActive BIT,
    IsSoftDeleted BIT,
    IsHardDeleted BIT,
    RowVersion INT,
    DeletedBy VARCHAR(50),
    DeletedDateTime DATETIME,
    SourceSystem VARCHAR(100),
    CreatedByIp VARCHAR(50),
    LastModifiedByIp VARCHAR(50),
    AuditId NVARCHAR(MAX),
    TenantId NVARCHAR(MAX),
    CorrelationId NVARCHAR(MAX)
);

CREATE TABLE IF NOT EXISTS Notifications_Audit (
    Id NVARCHAR(MAX) PRIMARY KEY,
    TableName VARCHAR(100),
    RecordID NVARCHAR(MAX),
    CreatedBy VARCHAR(50),
    CreatedDateTime DATETIME,
    LastModifiedBy VARCHAR(50),
    LastModifiedDateTime DATETIME,
    IsActive BIT,
    IsSoftDeleted BIT,
    IsHardDeleted BIT,
    RowVersion INT,
    DeletedBy VARCHAR(50),
    DeletedDateTime DATETIME,
    SourceSystem VARCHAR(100),
    CreatedByIp VARCHAR(50),
    LastModifiedByIp VARCHAR(50),
    AuditId NVARCHAR(MAX),
    TenantId NVARCHAR(MAX),
    CorrelationId NVARCHAR(MAX)
);

CREATE TABLE IF NOT EXISTS Nurses_Audit (
    Id NVARCHAR(MAX) PRIMARY KEY,
    TableName VARCHAR(100),
    RecordID NVARCHAR(MAX),
    CreatedBy VARCHAR(50),
    CreatedDateTime DATETIME,
    LastModifiedBy VARCHAR(50),
    LastModifiedDateTime DATETIME,
    IsActive BIT,
    IsSoftDeleted BIT,
    IsHardDeleted BIT,
    RowVersion INT,
    DeletedBy VARCHAR(50),
    DeletedDateTime DATETIME,
    SourceSystem VARCHAR(100),
    CreatedByIp VARCHAR(50),
    LastModifiedByIp VARCHAR(50),
    AuditId NVARCHAR(MAX),
    TenantId NVARCHAR(MAX),
    CorrelationId NVARCHAR(MAX)
);

CREATE TABLE IF NOT EXISTS Patients_Audit (
    Id NVARCHAR(MAX) PRIMARY KEY,
    TableName VARCHAR(100),
    RecordID NVARCHAR(MAX),
    CreatedBy VARCHAR(50),
    CreatedDateTime DATETIME,
    LastModifiedBy VARCHAR(50),
    LastModifiedDateTime DATETIME,
    IsActive BIT,
    IsSoftDeleted BIT,
    IsHardDeleted BIT,
    RowVersion INT,
    DeletedBy VARCHAR(50),
    DeletedDateTime DATETIME,
    SourceSystem VARCHAR(100),
    CreatedByIp VARCHAR(50),
    LastModifiedByIp VARCHAR(50),
    AuditId NVARCHAR(MAX),
    TenantId NVARCHAR(MAX),
    CorrelationId NVARCHAR(MAX)
);

CREATE TABLE IF NOT EXISTS Prescriptions_Audit (
    Id NVARCHAR(MAX) PRIMARY KEY,
    TableName VARCHAR(100),
    RecordID NVARCHAR(MAX),
    CreatedBy VARCHAR(50),
    CreatedDateTime DATETIME,
    LastModifiedBy VARCHAR(50),
    LastModifiedDateTime DATETIME,
    IsActive BIT,
    IsSoftDeleted BIT,
    IsHardDeleted BIT,
    RowVersion INT,
    DeletedBy VARCHAR(50),
    DeletedDateTime DATETIME,
    SourceSystem VARCHAR(100),
    CreatedByIp VARCHAR(50),
    LastModifiedByIp VARCHAR(50),
    AuditId NVARCHAR(MAX),
    TenantId NVARCHAR(MAX),
    CorrelationId NVARCHAR(MAX)
);

CREATE TABLE IF NOT EXISTS Referrals_Audit (
    Id NVARCHAR(MAX) PRIMARY KEY,
    TableName VARCHAR(100),
    RecordID NVARCHAR(MAX),
    CreatedBy VARCHAR(50),
    CreatedDateTime DATETIME,
    LastModifiedBy VARCHAR(50),
    LastModifiedDateTime DATETIME,
    IsActive BIT,
    IsSoftDeleted BIT,
    IsHardDeleted BIT,
    RowVersion INT,
    DeletedBy VARCHAR(50),
    DeletedDateTime DATETIME,
    SourceSystem VARCHAR(100),
    CreatedByIp VARCHAR(50),
    LastModifiedByIp VARCHAR(50),
    AuditId NVARCHAR(MAX),
    TenantId NVARCHAR(MAX),
    CorrelationId NVARCHAR(MAX)
);

CREATE TABLE IF NOT EXISTS Rooms_Audit (
    Id NVARCHAR(MAX) PRIMARY KEY,
    TableName VARCHAR(100),
    RecordID NVARCHAR(MAX),
    CreatedBy VARCHAR(50),
    CreatedDateTime DATETIME,
    LastModifiedBy VARCHAR(50),
    LastModifiedDateTime DATETIME,
    IsActive BIT,
    IsSoftDeleted BIT,
    IsHardDeleted BIT,
    RowVersion INT,
    DeletedBy VARCHAR(50),
    DeletedDateTime DATETIME,
    SourceSystem VARCHAR(100),
    CreatedByIp VARCHAR(50),
    LastModifiedByIp VARCHAR(50),
    AuditId NVARCHAR(MAX),
    TenantId NVARCHAR(MAX),
    CorrelationId NVARCHAR(MAX)
);

CREATE TABLE IF NOT EXISTS Shifts_Audit (
    Id NVARCHAR(MAX) PRIMARY KEY,
    TableName VARCHAR(100),
    RecordID NVARCHAR(MAX),
    CreatedBy VARCHAR(50),
    CreatedDateTime DATETIME,
    LastModifiedBy VARCHAR(50),
    LastModifiedDateTime DATETIME,
    IsActive BIT,
    IsSoftDeleted BIT,
    IsHardDeleted BIT,
    RowVersion INT,
    DeletedBy VARCHAR(50),
    DeletedDateTime DATETIME,
    SourceSystem VARCHAR(100),
    CreatedByIp VARCHAR(50),
    LastModifiedByIp VARCHAR(50),
    AuditId NVARCHAR(MAX),
    TenantId NVARCHAR(MAX),
    CorrelationId NVARCHAR(MAX)
);

CREATE TABLE IF NOT EXISTS Staff_Audit (
    Id NVARCHAR(MAX) PRIMARY KEY,
    TableName VARCHAR(100),
    RecordID NVARCHAR(MAX),
    CreatedBy VARCHAR(50),
    CreatedDateTime DATETIME,
    LastModifiedBy VARCHAR(50),
    LastModifiedDateTime DATETIME,
    IsActive BIT,
    IsSoftDeleted BIT,
    IsHardDeleted BIT,
    RowVersion INT,
    DeletedBy VARCHAR(50),
    DeletedDateTime DATETIME,
    SourceSystem VARCHAR(100),
    CreatedByIp VARCHAR(50),
    LastModifiedByIp VARCHAR(50),
    AuditId NVARCHAR(MAX),
    TenantId NVARCHAR(MAX),
    CorrelationId NVARCHAR(MAX)
);

CREATE TABLE IF NOT EXISTS Supplies_Audit (
    Id NVARCHAR(MAX) PRIMARY KEY,
    TableName VARCHAR(100),
    RecordID NVARCHAR(MAX),
    CreatedBy VARCHAR(50),
    CreatedDateTime DATETIME,
    LastModifiedBy VARCHAR(50),
    LastModifiedDateTime DATETIME,
    IsActive BIT,
    IsSoftDeleted BIT,
    IsHardDeleted BIT,
    RowVersion INT,
    DeletedBy VARCHAR(50),
    DeletedDateTime DATETIME,
    SourceSystem VARCHAR(100),
    CreatedByIp VARCHAR(50),
    LastModifiedByIp VARCHAR(50),
    AuditId NVARCHAR(MAX),
    TenantId NVARCHAR(MAX),
    CorrelationId NVARCHAR(MAX)
);

CREATE TABLE IF NOT EXISTS Surgeries_Audit (
    Id NVARCHAR(MAX) PRIMARY KEY,
    TableName VARCHAR(100),
    RecordID NVARCHAR(MAX),
    CreatedBy VARCHAR(50),
    CreatedDateTime DATETIME,
    LastModifiedBy VARCHAR(50),
    LastModifiedDateTime DATETIME,
    IsActive BIT,
    IsSoftDeleted BIT,
    IsHardDeleted BIT,
    RowVersion INT,
    DeletedBy VARCHAR(50),
    DeletedDateTime DATETIME,
    SourceSystem VARCHAR(100),
    CreatedByIp VARCHAR(50),
    LastModifiedByIp VARCHAR(50),
    AuditId NVARCHAR(MAX),
    TenantId NVARCHAR(MAX),
    CorrelationId NVARCHAR(MAX)
);

CREATE TABLE IF NOT EXISTS Transactions_Audit (
    Id NVARCHAR(MAX) PRIMARY KEY,
    TableName VARCHAR(100),
    RecordID NVARCHAR(MAX),
    CreatedBy VARCHAR(50),
    CreatedDateTime DATETIME,
    LastModifiedBy VARCHAR(50),
    LastModifiedDateTime DATETIME,
    IsActive BIT,
    IsSoftDeleted BIT,
    IsHardDeleted BIT,
    RowVersion INT,
    DeletedBy VARCHAR(50),
    DeletedDateTime DATETIME,
    SourceSystem VARCHAR(100),
    CreatedByIp VARCHAR(50),
    LastModifiedByIp VARCHAR(50),
    AuditId NVARCHAR(MAX),
    TenantId NVARCHAR(MAX),
    CorrelationId NVARCHAR(MAX)
);

CREATE TABLE IF NOT EXISTS Users_Audit (
    Id NVARCHAR(MAX) PRIMARY KEY,
    TableName VARCHAR(100),
    RecordID NVARCHAR(MAX),
    CreatedBy VARCHAR(50),
    CreatedDateTime DATETIME,
    LastModifiedBy VARCHAR(50),
    LastModifiedDateTime DATETIME,
    IsActive BIT,
    IsSoftDeleted BIT,
    IsHardDeleted BIT,
    RowVersion INT,
    DeletedBy VARCHAR(50),
    DeletedDateTime DATETIME,
    SourceSystem VARCHAR(100),
    CreatedByIp VARCHAR(50),
    LastModifiedByIp VARCHAR(50),
    AuditId NVARCHAR(MAX),
    TenantId NVARCHAR(MAX),
    CorrelationId NVARCHAR(MAX)
);

CREATE TABLE IF NOT EXISTS UserAccounts_Audit (
    Id NVARCHAR(MAX) PRIMARY KEY,
    TableName VARCHAR(100),
    RecordID NVARCHAR(MAX),
    CreatedBy VARCHAR(50),
    CreatedDateTime DATETIME,
    LastModifiedBy VARCHAR(50),
    LastModifiedDateTime DATETIME,
    IsActive BIT,
    IsSoftDeleted BIT,
    IsHardDeleted BIT,
    RowVersion INT,
    DeletedBy VARCHAR(50),
    DeletedDateTime DATETIME,
    SourceSystem VARCHAR(100),
    CreatedByIp VARCHAR(50),
    LastModifiedByIp VARCHAR(50),
    AuditId NVARCHAR(MAX),
    TenantId NVARCHAR(MAX),
    CorrelationId NVARCHAR(MAX)
);

CREATE TABLE IF NOT EXISTS Visits_Audit (
    Id NVARCHAR(MAX) PRIMARY KEY,
    TableName VARCHAR(100),
    RecordID NVARCHAR(MAX),
    CreatedBy VARCHAR(50),
    CreatedDateTime DATETIME,
    LastModifiedBy VARCHAR(50),
    LastModifiedDateTime DATETIME,
    IsActive BIT,
    IsSoftDeleted BIT,
    IsHardDeleted BIT,
    RowVersion INT,
    DeletedBy VARCHAR(50),
    DeletedDateTime DATETIME,
    SourceSystem VARCHAR(100),
    CreatedByIp VARCHAR(50),
    LastModifiedByIp VARCHAR(50),
    AuditId NVARCHAR(MAX),
    TenantId NVARCHAR(MAX),
    CorrelationId NVARCHAR(MAX)
);
